# Numpy 넘파이

목차
1. Numpy 특징
2. 배열의 생성
3. Numpy 슬라이싱 / 인덱싱
4. Numpy 연산
5. 실무에서 자주 쓰이는 것

### 용어
- axis : 배열의 각 축
- rank : 축의 개수
- shape : 축의 길이, 배열의 크기
```
[3 x 4 배열의 경우]

|-----------|
|1  3  2  7 |
|3  2  9  1 |
|4  6  8  1 |
|-----------|
axis 0 과 axis 1 을 갖는 2차원 배열 (이때 axis 0은 행, axis 1은 열을 나타낸다)
rank 2 array
shape는 (3, 4)
```

## Numpy 특징
---
- 과학 계산을 위한 라이브러리
- 행렬/배열 처리 및 연산
- 난수생성

## 배열의 생성
---
1. 리스트에서 행렬 / 배열 생성
- np.array() 함수를 사용해서 배열을 만든다.

- 배열의 차원 : ndim
- 배열의 크기 : shape
- 요소 자료형 확인 : dtype
- 배열의 접근

In [24]:
import numpy as np # numpy 패키지 로드하여 np로 사용

a = [[1,2,3], [4,5,6]] # 리스트에서 행렬생성
b = np.array(a) 
print(b) # 배열 보기
print("-----------")
print(b.ndim) # 배열의 차원
print(b.shape) # 배열의 크기
print(b.dtype) # 배열의 크기
print(b[0,0]) # 배열의 접근

[[1 2 3]
 [4 5 6]]
-----------
2
(2, 3)
int32
1


2. 특수한 배열의 생성

In [25]:
print(np.arange(10)) # 1씩 증가하는 1차원 배열(시작이 0부터)
print("-----------------------------")
print(np.arange(5, 10)) # 1씩 증가하는 1차원 배열(시작이 5부터)
print("-----------------------------")
print(np.zeros((2,2)))  # 영행렬 생성
print("-----------------------------")
print(np.ones((2,3)))  # 유닛행렬
print("-----------------------------")
print(np.full((2,3), 5)) # 모든 원소가 5인 2*3행렬
print("-----------------------------")
print(np.eye(3)) # 단위행렬

[0 1 2 3 4 5 6 7 8 9]
-----------------------------
[5 6 7 8 9]
-----------------------------
[[0. 0.]
 [0. 0.]]
-----------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
-----------------------------
[[5 5 5]
 [5 5 5]]
-----------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Reshape
- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있다..
- 배열에 포함된 요소가 사라지지 않는 형태라면 자유롭게 변환할 수 있다..
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 된다.

In [28]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2)

# 확인
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [30]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

# reshape(m, -1) 형태로 지정하여 Reshape 가능
print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


##  Numpy 슬라이싱 / 인덱싱
---

### 인덱싱
- 1차원 배열은 리스트와 방법이 같으므로 설명을 생략한다.
- **배열[행, 열]** 형태로 특정 위치의 요소를 조회한다.
- **배열[[행1,행2,..], :]** 또는 **배열[[행1,행2,..]]** 형태로 특정 행을 조회한다.
- **배열[:, [열1,열2,...]]** 형태로 특정 열을 조회한다.
- **배열[[행1,행2,...], [열1,열2,...]]** 형태로 특정 행의 특정 열을 조회한다.

In [37]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)      
print("-----------------------------")
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])
print("-----------------------------")
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])
print(a[[0, 1]])
print("-----------------------------")
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])
print("-----------------------------")
# 세 번째 행 두 번째 열의 요소 조회
print(a[[2], [1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------
2
-----------------------------
[[1 2 3]
 [4 5 6]]
-----------------------------
[[1 2]
 [4 5]
 [7 8]]
-----------------------------
[8]


### 슬라이싱
- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회한다.
- 조회 결과는 **2차원 배열**이 된다다.
- 마지막 **범위 값은 대상에 포함되지 않는다.**
- 즉, **배열[1:M, 2:N]**이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 된다.

In [39]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)    
print("-----------------------------")
# 첫 번째 ~ 두 번째 행 조회
# print(a[0:2, :])
print(a[0:2])
print("-----------------------------")
# 첫 번째 행, 첫 번째 ~ 두 번째 열 조회
print(a[0, 0:2])
print("-----------------------------")
# 첫 번째 ~ 세 번째 행, 두 번째 ~ 세 번째 열 조회
print(a[0:3, 1:3])
print("-----------------------------")
# 두 번째 ~ 끝 행, 두 번째 ~ 끝 열 조회
print(a[1:, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------
[[1 2 3]
 [4 5 6]]
-----------------------------
[1 2]
-----------------------------
[[2 3]
 [5 6]
 [8 9]]
-----------------------------
[[5 6]
 [8 9]]


##### 조건 조회
- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부른다.
- 조회 결과는 **1차원 배열**이 된다.
- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회한다.

In [42]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)
print("-----------------------------")
# 요소 중에서 90 이상인 것만 조회
print(score[score >= 90])

[[78 91 84 89 93 65]
 [82 87 96 79 91 73]]
-----------------------------
[91 93 96 91]


- 검색 조건을 변수로 선언해 사용할 수 있다.

In [43]:
# 요소 중에서 90 이상인 것만 조회
condition = score >= 90
print(score[condition])

[91 93 96 91]


- 여러 조건을 & 와 | 로 연결하여 조회할 수 있습니다.

In [45]:
# 모든 요소 중에서 90 이상 95 미만인 것만 조회
print(score[(score >= 90) & (score <= 95)])

[91 93 91]


## Numpy 연산
---
- 배열간 연산 가능
- [ +, -, *, / ]등의 연산자 사용 가능

In [51]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print("배열 확인하기")
print(x)
print(y)
print("-----------------------------")
# 배열 더하기
print("배열 더하기")
print(x + y)

# 또는
print(np.add(x, y))
print("-----------------------------")
# 배열 빼기
print("배열 빼기")
print(x - y)

# 또는
print(np.subtract(x, y))
print("-----------------------------")
# 배열 곱하기
print("배열 곱하기")
print(x * y)

# 또는
print(np.multiply(x, y))
print("-----------------------------")
# 배열 나누기
print("배열 나누기")
print(x / y)

# 또는
print(np.divide(x, y))

배열 확인하기
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
-----------------------------
배열 더하기
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
-----------------------------
배열 빼기
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
-----------------------------
배열 곱하기
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
-----------------------------
배열 나누기
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


- dot() 함수 : 행렬의 곱
- sum() 함수 : 모든 원소의 합
- prod() 함수 : 모든 원소의 곱
- mean() 함수 : 모든 원소의 평균
- std() 함수 : 모든 원소의 표준 편차

In [57]:
arr1 = [[1,2],[3,4]]
arr2 = [[5,6],[7,8]]
a = np.array(arr1)
b = np.array(arr2)

c= np.dot(a, b)

print("행렬의 곱")
print(c)

print("모든 원소의 합")
print(np.sum(a)) 

print('모든 원소의 곱') 
print(np.prod(a)) 

print('모든 원소의 평균') 
print(np.mean(a)) 

print('모든 원소의 표준편차') 
print(np.std(a)) 


행렬의 곱
[[19 22]
 [43 50]]
모든 원소의 합
10
모든 원소의 곱
24
모든 원소의 평균
2.5
모든 원소의 표준편차
1.118033988749895


## 실무에서 자주 쓰이는 것
---

1. 배열 집계 함수
- np.sum(), 혹은 array.sum()
    - axis = 0 : 열 기준 집계
    - axis = 1 : 행 기준 집계
    - 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()
- np.argmax() : 전체에서 최대값의 인덱스
- np.argmin() : 전체에서 최소값의 인덱스

In [61]:
# array를 생성합니다.
a = np.array([[1,5,7],[2,3,8]])
print(a)
# 전체 집계
print(f"전체 집계 : {np.sum(a)}")

# 열기준 집계
print(f"열기준 집계 : {np.sum(a, axis = 0)}")

# 행기준 집계
print(f"행기준 집계 : {np.sum(a, axis = 1)}")

# 전체 중에서 가장 큰 값의 인덱스
print(f"전체 중에서 가장 큰 값의 인덱스{np.argmax(a)}")
print(f"전체 중에서 가장 작은 값의 인덱스{np.argmin(a)}")

# 행 방향 최대값의 인덱스
print(f"행 방향 최대값의 인덱스 : {np.argmax(a, axis = 0)}")

# 열 방향 최대값의 인덱스
print(f"열 방향 최대값의 인덱스 : {np.argmax(a, axis = 1)}")


[[1 5 7]
 [2 3 8]]
전체 집계 : 26
열기준 집계 : [ 3  8 15]
행기준 집계 : [13 13]
전체 중에서 가장 큰 값의 인덱스5
전체 중에서 가장 작은 값의 인덱스0
행 방향 최대값의 인덱스 : [1 0 1]
열 방향 최대값의 인덱스 : [2 2]


2. np.where
- np.where(조건문, True일때 값, False일 때 값)

In [63]:
# 선언
a = np.array([1,3,2,7])

# 조건
np.where(a > 2, 1, 0)

array([0, 1, 0, 1])