# Tokenize 토큰화

```
text = "아들아 너는 계획이 다"
tokens = 토큰화.숫자로(text)
# [ 2656, 47485, 1681, 47441, 10635, 148]
outputs = 다음토큰(tokens) # 결과: 나올 수 있는 모든 토큰의
확률값
token = 가장높은확률의토큰(outputs)
# 605
decoded = 토큰화.단어로(token)
# 있어
```

In [1]:
#!pip install transformers -q

In [2]:
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast

# 토큰화 함수
tokenizer = PreTrainedTokenizerFast.from_pretrained("taeminlee/kogpt2")
# 다음 단어 함수
model = GPT2LMHeadModel.from_pretrained("taeminlee/kogpt2")

C:\Users\user\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\user\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.


In [3]:
text = "아들아 너는 계획이 다 있어"
tokens = tokenizer.encode(text, return_tensors="pt")
tokens

tensor([[ 2656, 47485,  1681, 47441, 10635,   148,   605]])

In [8]:
outputs = model(tokens) # 모든 토큰들의 확률값
print(outputs[0].shape)
outputs = outputs[0][0, -1, :]
print(outputs)
print(outputs[605])
len(outputs)

torch.Size([1, 7, 50000])
tensor([  0.8397,  10.9158, -12.0285,  ...,  -5.1338,  -1.9830,  -1.5586],
       grad_fn=<SliceBackward0>)
tensor(6.1770, grad_fn=<SelectBackward0>)


50000

In [9]:
token = outputs.argmax(-1) # 가장 높은 확률의 토큰
decoded = tokenizer.decode(token)
print(token, decoded)

tensor(1) </s>


In [11]:
for t in range(600,610):
    print(t, tokenizer.decode(t))

600 운데
601 되었다
602 최고
603 기에
604 항
605 있어
606 이라는
607 넘
608 폭
609 번


In [12]:
from transformers import GPT2LMHeadModel, PreTrainedTokenizerFast
# 토큰화 함수
tokenizer = PreTrainedTokenizerFast.from_pretrained("taeminlee/kogpt2")
# 다음 단어 함수
model = GPT2LMHeadModel.from_pretrained("taeminlee/kogpt2")
text = "아들아 너는 계획이 다"
tokens = tokenizer.encode(text, return_tensors="pt")
outputs = model.generate(tokens)
print(outputs[0])
generated_text = tokenizer.decode(outputs[0])
print(generated_text)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'GPT2Tokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
C:\Users\user\anaconda3\Lib\site-packages\transformers\generation\utils.py:1260: UserWarning: Using the model-agnostic default `max_length` (=20) to control thegeneration length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([ 2656, 47485,  1681, 47441, 10635,   148,   605,     1,     0,   155,
          872,  7892,  8274,   605,     1,     0,   155,   872,  7892,  8274])
아들아 너는 계획이 다 있어</s><s> 나 지금 집에 가고 있어</s><s> 나 지금 집에 가고
